package no.ebakke.studycaster.util;

import java.awt.Canvas;
import java.awt.Image;
import java.awt.MediaTracker;
import java.lang.reflect.InvocationTargetException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

public class ImageDebugFrame extends JFrame {
  private static final long serialVersionUID = 1L;
  private static boolean lfSetYet = false;
  private final Icon image;

  public static void showImage(final Image image) {
    if (!lfSetYet) {
      try {
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      } catch (Exception e) { }
      lfSetYet = true;
    }
    try {
      SwingUtilities.invokeAndWait(new Runnable() {
        public void run() {
          ImageSelection.copyImageToClipBoard(image);
          new ImageDebugFrame(image).setVisible(true);
        }
      });
    } catch (InterruptedException e) {
      System.err.println("Interrupted!");
      Thread.currentThread().interrupt();
    } catch (InvocationTargetException e) {
      if (e.getCause() instanceof Error) {
        throw (Error) e.getCause();
      } else if (e.getCause() instanceof RuntimeException) {
        throw (RuntimeException) e.getCause();
      }
      e.printStackTrace();
    }
  }

  /** Creates new form ImageDebugFrame */
  public ImageDebugFrame(Image image) {
    MediaTracker mt = new MediaTracker(new Canvas());
    mt.addImage(image, 0);
    try {
      mt.waitForAll();
    } catch (InterruptedException e) {
      System.err.println("Interrupted!");
      Thread.currentThread().interrupt();
    }
    this.image = new ImageIcon(image);
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Image Viewer");

        imageLabel.setIcon(this.image);
        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.controlDkShadow));
        scrollPane.setViewportView(imageLabel);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
