package no.ebakke.studycaster.ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import no.ebakke.studycaster.backend.StudyCasterException;
import no.ebakke.studycaster.configuration.UIStringKey;
import no.ebakke.studycaster.configuration.UIStrings;

public class ConfirmationCodeDialogPanel extends javax.swing.JPanel {
  private static final Logger LOG = Logger.getLogger("no.ebakke.studycaster");

  public ConfirmationCodeDialogPanel(UIStrings strings) {
    initComponents();
    boxLabel.setText(strings.getString(UIStringKey.DIALOG_CONFIRMATION_CODEBOX_LABEL));
    boxLabel.setDisplayedMnemonic(strings.getMnemonic(UIStringKey.DIALOG_CONFIRMATION_CODEBOX_LABEL));
    clipboardLabel.setText(strings.getString(UIStringKey.DIALOG_CONFIRMATION_CLIPBOARD_MESSAGE));
  }

  public void setConfirmationCode(String code) {
    codeBox.setText(code);
    try {
      UIUtil.copyStringToClipboard(code);
      clipboardLabel.setVisible(true);
    } catch (StudyCasterException e) {
      LOG.log(Level.WARNING, "Failed to copy confirmation code to clipboard", e);
      clipboardLabel.setVisible(false);
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        boxLabel = new javax.swing.JLabel();
        codeBox = new javax.swing.JTextField();
        clipboardLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        boxLabel.setDisplayedMnemonic('U');
        boxLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boxLabel.setLabelFor(codeBox);
        boxLabel.setText("Upload successful! Your confirmation code is...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(boxLabel, gridBagConstraints);

        codeBox.setEditable(false);
        codeBox.setFont(codeBox.getFont().deriveFont(codeBox.getFont().getStyle() | java.awt.Font.BOLD, codeBox.getFont().getSize()+7));
        codeBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codeBox.setText("1234567890");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(codeBox, gridBagConstraints);

        clipboardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clipboardLabel.setText("(The code has been copied to the clipboard so you can paste it into the HIT.)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(clipboardLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boxLabel;
    private javax.swing.JLabel clipboardLabel;
    private javax.swing.JTextField codeBox;
    // End of variables declaration//GEN-END:variables
}
