package no.ebakke.studycaster.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import javax.swing.JDialog;

public class ConfirmationCodeDialog extends JDialog {
    private static final long serialVersionUID = -6641082431235013732L;

    public static void show(Window parent, String confcode) {
      new ConfirmationCodeDialog(parent, confcode).setVisible(true);
    }

    private ConfirmationCodeDialog(Window parent, String confcode) {
        super(parent);
        initComponents();
        codeBox.setText(confcode);
        Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
        cb.setContents(new StringSelection(confcode), new ClipboardOwner() {
          public void lostOwnership(Clipboard clipboard, Transferable contents) {
          }
        });
        okButton.requestFocusInWindow();

        Dimension sdim = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension wdim = getSize();
        /* Since the dialog will be modal, offset it slightly from the center so it
        will be less likely to cover up other application's dialogs.  */
        setLocation((sdim.width - wdim.width) / 2, (sdim.height - wdim.height) / 2 - 200);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    label1 = new javax.swing.JLabel();
    codeBox = new javax.swing.JTextField();
    label2 = new javax.swing.JLabel();
    okButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Upload Successful");
    setModal(true);
    setResizable(false);

    label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label1.setText("Upload successful! Your confirmation code is...");

    codeBox.setEditable(false);
    codeBox.setFont(codeBox.getFont().deriveFont(codeBox.getFont().getStyle() | java.awt.Font.BOLD, codeBox.getFont().getSize()+7));
    codeBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    codeBox.setText("1234567890");

    label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label2.setText("(The number has been copied to the clipboard so you can paste it into the HIT.)");

    okButton.setMnemonic('O');
    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(codeBox, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
          .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
          .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(okButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(codeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(okButton)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
      dispose();
    }//GEN-LAST:event_okButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField codeBox;
  private javax.swing.JLabel label1;
  private javax.swing.JLabel label2;
  private javax.swing.JButton okButton;
  // End of variables declaration//GEN-END:variables

}
